kind: pipeline
type: docker
name: nextjs-ci

steps:
  - name: Install dependencies
    image: node:20-alpine
    commands:
      - npm install

  - name: Lint
    image: node:20-alpine
    environment:
      WEBHOOK_URL:
        from_secret: WEBHOOK_URL
    commands:
      - echo $WEBHOOK_URL
      - npm run lint


  - name: Build
    image: node:20-alpine
    commands:
      - npm run build
      
  - name: Deploy
    image: plugins/webhook
    environment:
      WEBHOOK_URL:
        from_secret: WEBHOOK_URL
    settings:
      urls:
        - $WEBHOOK_URL
      content_type: application/json
      method: POST
  
trigger:
  event: 
    - push
    - pull_request


