kind: pipeline
type: docker
name: nextjs-ci

steps:
  - name: install-dependencies
    image: node:20-alpine
    commands:
      - npm install -g pnpm
      - pnpm install --frozen-lockfile

  - name: lint
    image: node:20-alpine
    commands:
      - npm run lint

  - name: build
    image: node:20-alpine
    commands:
      - npm run build

trigger:
  branch:
    - main
