kind: pipeline
type: docker
name: nextjs-ci

steps:
  # - name: Install dependencies
  #   image: node:20-alpine
  #   commands:
  #     - npm install

  # - name: Lint
  #   image: node:20-alpine
  #   commands:
  #     - npm run lint

  # - name: Build
  #   image: node:20-alpine
  #   commands:
  #     - npm run build
      
  - name: Deploy
    image: plugins/webhook
    environment:
      WEBHOOK_URL:
        from_secret: ${WEBHOOK_URL}
      WebhookID:
        from_secret: WebhookID
    settings:
      urls: $WEBHOOK_URL
      content_type: application/json
      method: POST
  
trigger:
  event: 
    - push
    - pull_request


