kind: pipeline
type: docker
name: nextjs-ci

steps:
  - name: Install dependencies
    image: node:20-alpine
    commands:
      - npm install

  - name: Lint
    image: node:20-alpine
    commands:
      - npm run lint

  - name: Build
    image: node:20-alpine
    commands:
      - npm run build
      
  - name: Deploy
    image: plugins/webhook
    settings:
      urls:
        - https://portainer.abhayramesh.com/api/stacks/webhooks/97af7e95-f2ce-4ea9-b3c2-97d49ad44b0c
      content_type: application/json
      method: POST
  
trigger:
  event: 
    - push
    - pull_request


