version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:3000'
    volumes:
      - app-data:/app/node_modules
    environment:
      - NODE_ENV=production

volumes:
  app-data:
