version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    restart: always
    ports:
      - '6359:3000'
    volumes:
      - app-data:/app

volumes:
  app-data:

networks:
  default:
    name: web
    external: true
