version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    restart: always
    ports:
      - '6359:3000'

networks:
  default:
    name: web
    external: true
