version: '3'
services:
  abhay-portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '6359:3000'
    volumes:
      - app-data:/app/node_modules

volumes:
  app-data:

networks:
  default:
    name: web
    external: true  

